### ISSUE TITLE
@Setter를 사용하여 null 값을 받아 발생하는 예외를 해결해주었습니다. 해결방안에 대한 코멘트를 듣고 싶습니다. 

### ISSUE THREAD

**Issue by mansooonuna** [mansooonuna/hanghaeblog#1]
(https://github.com/mansooonuna/hanghaeblog/commit/33771162f66c7e6778243f98999c32ebc42806f3)

 - requestDto에 title, contents  만 넣어서 객체를 보내니 post entity의 필수값인 username에 null 값이 입력되어 
 org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]
예외가 계속해서 발생했습니다.

해결방법으로 @Setter 어노테이션을 이용해 post 의 username 을 토큰을 통해 받은 user의 username으로 설정해주었습니다.

**Comment by taetoo** [comment]
<img width="425" alt="스크린샷 2023-04-20 오후 11 26 55" src="https://user-images.githubusercontent.com/101050600/233397230-2d8d3bf4-0d50-44a5-9eda-6f687fa744b2.png">
다솜님의 postService 코드 하단 88번째 줄, request에서 토큰 가져오는 부분 로직을 이용해보면 어떨까요? 굳이 setter 안쓰고도 토큰에서 유저정보 가져올 수 있다고 생각이되거든요!!😊
멘토링 시 setter를 지양하는 이유에 대해서는 설명드렸으니, 한번 위의 첨부한 이미지 안에 코드를 이용해서 유저정보 가져오는 부분 수정해 보시면 좋을 것 같습니다!
